### PR TITLE
Protect against Regex-Denial-of-Service attack by doing timebound matching

### PR DESCRIPTION
**Pull request by jaihind213**
Prevent against Regex Denial of Service attack.

o- some robots.txt have rules like "Allow: **********.css"
o- so regex matching a url against such a rule can take years to complete.
o- this pr is about introducing a time limit while doing regex matching.
Note:
o- if some rules in robots.txt  evaluate negative & some time out, then we throw an exception to caller to indicate that the we could not evaluate all rules properly, so that he may choose what to do.
o- if some rules in robots.txt  evaluate positive & some time out, then no exception is thrown(i.e. timeouts are ignored)
o- if all rules in robots.txt  evaluate negative, then no exception is thrown.

reference:
https:// www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

### CODE REVIEW

**Comment by jaihind213** [comment]
@pandzel kindly review.

**Comment by pandzel** [comment]
Great job. Thank you very much.

**Comment by jaihind213** [comment]
hi @pandzel 

i noticed that you removed from the signature the thrown matchingexception from query() ask() grant()..  the strategy catches the timeout exception and returns false

it makes sense because the job of matcher is to match or not match and ya i felt it kind of makes the signature messy.

i thought perhaps we can let the user know why matching is not occurring. hence i propagated the exception. else its kind of hidden. 

perhaps some sort of log info/debug statement ?

let me know your thoughts ?

**Comment by pandzel** [comment]
About throwing exception: what you mentioned is one thing, but there is more.
Once published interface cannot be changed. It's a basic design principle. Otherwise, somebody else's code won't compile.

**Pull request merged**
