### PR TITLE
Change access modifier of Matching/Winning Strategies 

### PR DESCRIPTION
**Pull request by jaihind213**
o- for ppl to use while calling the utility helper method read() in RobotsTxt.java
o- for ppl to create and use their own strategies.
o- for now, print to std err, that matching timeout occurred instead of swallowing the exception.

Note: 
1) access modifier for Access.java has changed because Winning Strategy  has been changed to public.
2) forgot to make this change while submitting "github.com/pandzel/RobotsTxt/pull/8"

### CODE REVIEW

**Comment by jaihind213** [comment]
hi @pandzel 

kindly request you to review. 

Also wanted your thoughts on why timeout exception should not be propagated to the user.

thanking you
with regards,
ch Vishnu

**Comment by jaihind213** [comment]
hi @pandzel 

thank you for your thoughts. i shall remove the println.

may I suggest then, we change the signature of 

static RobotsTxt read(InputStream input, MatchingStrategy matchingStrategy, WinningStrategy winningStrategy)

to

static RobotsTxt read(InputStream input, int matchingTimeoutMs)

Since the access modifier is not public for the strategy classes, else the user call that utility method from his class and then cant benefit from the timeout strategy.

thanking you
with regards,
ch Vishnu

**Comment by pandzel** [comment]
@jaihind213 

I did something different: made default matching strategy to use timing matcher by default (with default timeout).

**Comment by jaihind213** [comment]
hi @pandzel 

Thanks for the change.

just a suggestion, if possible timeout should be configurable. helpful for low latency systems as they might want a more aggressive timeout.

with regards,
ch Vishnu

**Comment by jaihind213** [comment]
hi @pandzel 

kindly request you to publish the latest artifact to mvn repo.

thanking you

with regards,
ch Vishnu

**Comment by pandzel** [comment]
@jaihind213 

Will publish as soon as I find some spare time. Thank's again for your great contribution. I will make timeout configurable through environment variable (and keep API clean and simple).

**Pull request closed without merging**
